version: '2.1'

services:
  ghost:
    image: ghost:1.25.2-alpine
    volumes:
      - ./content:/var/lib/ghost/content
    ports:
      - 2368:2368

  buster:
    image: goposky/buster
    command: /buster.sh
    volumes:
      - ./static:/static
      - ./buster.sh:/buster.sh
      - ./header.html:/header.html

  preview:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 2369:80
